# Default configuration for splintercat
# This file includes other default configurations

include:
  - commands.yaml
  - prompts.yaml
  - agents.yaml
  - tools.yaml

config:
  # Default strategy settings
  strategy:
    name: batch
    batch_size: 10
    max_retries: 3
