# Default configuration for splintercat
# This file includes other default configurations

include:
  - commands.yaml
  - prompts.yaml
  - agents.yaml
  - tools.yaml

config:
  # Agent log directory for execution traces (platform-specific)
  agent_log_dir: "{platformdirs.user_log_dir}"

  # Default strategy settings
  strategy:
    name: batch
    batch_size: 10
    max_retries: 3
