source:
  repo: https://github.com/llvm/llvm-project.git
  branch: main
  workdir: /home/jbyrd/git/llvm-mos
  limit: 100

target:
  branch: stable-test
  base_ref: main
  workdir: /home/jbyrd/git/llvm-mos
  force_recreate: true

test_command: echo cd {workdir}/build && echo ninja

strategy: greedy
interactive: false
