source:
  repo: https://github.com/llvm/llvm-project.git
  branch: main
  workdir: /home/jbyrd/git/llvm-mos

target:
  branch: stable
  start_point: feature/enable-workflow-variable
  workdir: /home/jbyrd/git/llvm-mos

test_command: cd {workdir}/build && ninja

interactive: false
