source:
  repo: https://github.com/llvm/llvm-project.git
  branch: main
  workdir: /home/jbyrd/git/llvm-mos
  limit: 500

target:
  branch: stable-test
  base_ref: main
  workdir: /home/jbyrd/git/llvm-mos
  force_recreate: true

test_command: echo cd {workdir}/build && ninja

interactive: false
